Repository SkillsFundingAgency/das-admin-service, pull requests merged in 2019-10, with the labels that each got.

#60 On 2091 aad feedback and review
  src/SFA.DAS.AdminService.Web.sln
  src/SFA.DAS.AdminService.Web/Controllers/Apply/ApplicationController.cs
  src/SFA.DAS.AdminService.Web/Controllers/Apply/FinancialController.cs
  src/SFA.DAS.AdminService.Web/Helpers/ApplicationReviewHelpers.cs
  src/SFA.DAS.AdminService.Web/Infrastructure/ApiClient.cs
  src/SFA.DAS.AdminService.Web/Infrastructure/IApiClient.cs
  src/SFA.DAS.AdminService.Web/SFA.DAS.AdminService.Web.csproj
  src/SFA.DAS.AdminService.Web/ViewModels/Apply/Applications/ApplicationReturnedViewModel.cs
  src/SFA.DAS.AdminService.Web/ViewModels/Apply/Applications/ApplicationSequenceAssessmentViewModel.cs
  src/SFA.DAS.AdminService.Web/ViewModels/Apply/Applications/SectionViewModel.cs
  src/SFA.DAS.AdminService.Web/ViewModels/Apply/Applications/SequenceViewModel.cs
  src/SFA.DAS.AdminService.Web/Views/Apply/Applications/Assessment.cshtml
  src/SFA.DAS.AdminService.Web/Views/Apply/Applications/ClosedApplications.cshtml
  src/SFA.DAS.AdminService.Web/Views/Apply/Applications/MidpointApplications.cshtml
  src/SFA.DAS.AdminService.Web/Views/Apply/Applications/Page.cshtml
  src/SFA.DAS.AdminService.Web/Views/Apply/Applications/Page_ReadOnly.cshtml
  src/SFA.DAS.AdminService.Web/Views/Apply/Applications/RejectedApplications.cshtml
  src/SFA.DAS.AdminService.Web/Views/Apply/Applications/Returned.cshtml
  src/SFA.DAS.AdminService.Web/Views/Apply/Applications/Section.cshtml
  src/SFA.DAS.AdminService.Web/Views/Apply/Applications/Section_ReadOnly.cshtml
  src/SFA.DAS.AdminService.Web/Views/Apply/Applications/Sequence.cshtml
  src/SFA.DAS.AdminService.Web/Views/Apply/Applications/Sequence_ReadOnly.cshtml
  src/SFA.DAS.AdminService.Web/Views/Apply/Applications/StandardApplications.cshtml
  src/SFA.DAS.AdminService.Web/Views/Apply/Financial/Application.cshtml
  src/SFA.DAS.AdminService.Web/Views/Apply/Financial/Application_ReadOnly.cshtml
  src/SFA.DAS.AdminService.Web/Views/Apply/Financial/ClosedApplications.cshtml
  src/SFA.DAS.AdminService.Web/Views/Apply/Financial/OpenApplications.cshtml
  src/SFA.DAS.AdminService.Web/Views/Apply/Financial/RejectedApplications.cshtml
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/IQnaApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/QnaApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/SFA.DAS.AssessorService.Application.Api.Client.csproj
  src/SFA.DAS.AssessorService.ApplyTypes/ApplicationReviewStatus.cs
  src/SFA.DAS.AssessorService.ApplyTypes/ApplicationSequence.cs
  src/SFA.DAS.AssessorService.ApplyTypes/ApplicationStatus.cs
  src/SFA.DAS.AssessorService.ApplyTypes/ApplicationSummaryItem.cs
  src/SFA.DAS.AssessorService.ApplyTypes/FinancialApplicationSummaryItem.cs
  src/SFA.DAS.AssessorService.ApplyTypes/FinancialReviewStatus.cs
  src/SFA.DAS.AssessorService.ApplyTypes/SFA.DAS.AssessorService.ApplyTypes.csproj
Labels: Do Not Merge

#65 ON-2151 Display the completion status for the learner
  src/SFA.DAS.AdminService.Web/Views/Search/Select.cshtml
  src/SFA.DAS.AssessorService.Api.Types/Models/LearnerDetail.cs
Labels: Ready for Release, Tested

#64 ON-2269 Title and status property updated on the 'View organisation' page
  src/SFA.DAS.AdminService.Web/Views/Register/ViewOrganisation.cshtml
Labels: Tested

#62 On 2287 admin service manage users
  src/SFA.DAS.AdminService.Web.Extensions/TagHelpers/RoleTagHelper.cs
  src/SFA.DAS.AdminService.Web.Tests/Controllers/CertificateTests/CertificateAmendQueryBase.cs
  src/SFA.DAS.AdminService.Web.Tests/Controllers/CertificateTests/Given_I_request_the_AdddressPage.cs
  src/SFA.DAS.AdminService.Web.Tests/Controllers/CertificateTests/Given_I_request_the_options_page.cs
  src/SFA.DAS.AdminService.Web.Tests/Controllers/CertificateTests/WhenUserLoadsAmendOptionPage.cs
  src/SFA.DAS.AdminService.Web.Tests/Controllers/CertificateTests/WhenUserLoadsAmendsAddressPage.cs
  src/SFA.DAS.AdminService.Web.Tests/Controllers/CertificateTests/WhenUserLoadsAmendsDatePage.cs
  src/SFA.DAS.AdminService.Web.Tests/Controllers/CertificateTests/WhenUserLoadsAmendsGradePage.cs
  src/SFA.DAS.AdminService.Web.Tests/Controllers/CertificateTests/WhenUserLoadsAmendsRecipientPage.cs
  src/SFA.DAS.AdminService.Web.Tests/Controllers/Register/Given_I_request_view_organisation_page.cs
  src/SFA.DAS.AdminService.Web.Tests/Controllers/Register/RegisterBase.cs
  src/SFA.DAS.AdminService.Web.sln
  src/SFA.DAS.AdminService.Web/AutoMapperProfiles/RegisterViewAndEditUserViewModelProfile.cs
  src/SFA.DAS.AdminService.Web/Automapper/CustomResolvers/ApprovalsViewModelResolver.cs
  src/SFA.DAS.AdminService.Web/Controllers/RegisterController.cs
  src/SFA.DAS.AdminService.Web/Controllers/RegisterUserController.cs
  src/SFA.DAS.AdminService.Web/Extensions/ControllerExtensions.cs
  src/SFA.DAS.AdminService.Web/Infrastructure/MappingStartup.cs
  src/SFA.DAS.AdminService.Web/Models/PermissionsViewModels.cs
  src/SFA.DAS.AdminService.Web/Models/RegisterViewAndEditOrganisationViewModel.cs
  src/SFA.DAS.AdminService.Web/Models/RegisterViewAndEditUserViewModel.cs
  src/SFA.DAS.AdminService.Web/Models/UserRemovedViewModel.cs
  src/SFA.DAS.AdminService.Web/Views/Register/EditOrganisation.cshtml
  src/SFA.DAS.AdminService.Web/Views/Register/EditUserPermissions.cshtml
  src/SFA.DAS.AdminService.Web/Views/Register/RemoveConfirm.cshtml
  src/SFA.DAS.AdminService.Web/Views/Register/Removed.cshtml
  src/SFA.DAS.AdminService.Web/Views/Register/ViewContact.cshtml
  src/SFA.DAS.AdminService.Web/Views/Register/ViewOrganisation.cshtml
  src/SFA.DAS.AdminService.Web/Views/Register/ViewUser.cshtml
  src/SFA.DAS.AdminService.Web/Views/Register/_UserDetails.cshtml
  src/SFA.DAS.AssessorService.Api.Types/Models/ContactIncludePrivilegesResponse.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/ContactsWithPrivilegesResponse.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/GetAllContactsIncludePrivilagesRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/GetAllContactsRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/GetContactsWhoCanBePrimaryForOrganisationRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/GetContactsWithPrivilagesRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/NotifyUserManagementUsersRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/PrivilegeResponse.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/Register/UpdateEpaOrganisationAddressRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/Register/UpdateEpaOrganisationEmailRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/Register/UpdateEpaOrganisationPhoneNumberRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/Register/UpdateEpaOrganisationPrimaryContactRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/Register/UpdateEpaOrganisationWebsiteLinkRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/SignInCallback.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/UserManagement/ApproveContactRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/UserManagement/InviteContactToOrganisationRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/UserManagement/InviteContactToOrganisationResponse.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/UserManagement/RemoveContactFromOrganisationRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/UserManagement/RemoveContactFromOrganisationResponse.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/UserManagement/RequestForPrivilegeRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/UserManagement/SetContactPrivilegesRequest.cs
  src/SFA.DAS.AssessorService.Api.Types/Models/UserManagement/SetContactPrivilegesResponse.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/ContactsApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/IContactsApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/IOrganisationsApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api.Client/Clients/OrganisationsApiClient.cs
Labels: Tested

#61 ON-2316 - tech and data email address
  src/SFA.DAS.AdminService.Web/Views/Reports/Index.cshtml
Labels: Tested
