Repository SkillsFundingAgency/das-admin-service, pull requests merged in 2019-09, with the labels that each got.

#44 Apr 671 remove structuremap
  src/SFA.DAS.AdminService.Web/Extensions/ServiceCollectionExtensions.cs
  src/SFA.DAS.AdminService.Web/SFA.DAS.AdminService.Web.csproj
  src/SFA.DAS.AdminService.Web/Startup.cs
  src/SFA.DAS.AdminService.Web/Views/Roatp/Index.cshtml
  src/SFA.DAS.AssessorService.Application.Api.External/AutoMapperProfiles/BatchCertificateRequestProfile.cs
  src/SFA.DAS.AssessorService.Application.Api.External/AutoMapperProfiles/BatchCertificateResponseProfile.cs
  src/SFA.DAS.AssessorService.Application.Api.External/AutoMapperProfiles/CertificateDataProfile.cs
  src/SFA.DAS.AssessorService.Application.Api.External/AutoMapperProfiles/CertificateProfile.cs
  src/SFA.DAS.AssessorService.Application.Api.External/AutoMapperProfiles/CertificateStatusProfile.cs
  src/SFA.DAS.AssessorService.Application.Api.External/AutoMapperProfiles/GetCertificateResponseProfile.cs
  src/SFA.DAS.AssessorService.Application.Api.External/AutoMapperProfiles/SubmitBatchCertificateRequestProfile.cs
  src/SFA.DAS.AssessorService.Application.Api.External/AutoMapperProfiles/SubmitBatchCertificateResponseProfile.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Controllers/CertificateController.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Controllers/PingController.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Infrastructure/ApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Infrastructure/IApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Infrastructure/SandboxApiClient.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Messages/BatchCertificateRequest.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Messages/BatchCertificateResponse.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Messages/DeleteCertificateRequest.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Messages/GetCertificateRequest.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Messages/GetCertificateResponse.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Messages/SubmitBatchCertificateRequest.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Messages/SubmitBatchCertificateResponse.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Middleware/ApiResponse.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Middleware/GetHeadersMiddleware.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Middleware/HeaderInfo.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Middleware/IHeaderInfo.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Middleware/SandboxHeadersMiddleware.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Models/Certificates/Certificate.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Models/Certificates/CertificateData.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Models/Certificates/CreateCertificate.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Models/Certificates/Created.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Models/Certificates/Learner.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Models/Certificates/LearningDetails.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Models/Certificates/PostalContact.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Models/Certificates/Printed.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Models/Certificates/Standard.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Models/Certificates/Status.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Models/Certificates/SubmitCertificate.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Models/Certificates/Submitted.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Models/Certificates/UpdateCertificate.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Program.cs
  src/SFA.DAS.AssessorService.Application.Api.External/Properties/launchSettings.json
  src/SFA.DAS.AssessorService.Application.Api.External/SFA.DAS.AssessorService.Application.Api.External.csproj
  src/SFA.DAS.AssessorService.Application.Api.External/Startup.cs
  src/SFA.DAS.AssessorService.Application.Api.External/StartupConfiguration/MappingStartup.cs
  src/SFA.DAS.AssessorService.Application.Api.External/SwaggerHelpers/Examples/ApiResponseExample.cs
  src/SFA.DAS.AssessorService.Application.Api.External/SwaggerHelpers/Examples/BatchCertificateResponseExample.cs
  src/SFA.DAS.AssessorService.Application.Api.External/SwaggerHelpers/Examples/CertificateExample.cs
  src/SFA.DAS.AssessorService.Application.Api.External/SwaggerHelpers/Examples/CreateCertificateExample.cs
  src/SFA.DAS.AssessorService.Application.Api.External/SwaggerHelpers/Examples/SubmitBatchCertificateResponseExample.cs
  src/SFA.DAS.AssessorService.Application.Api.External/SwaggerHelpers/Examples/SubmitCertificateExample.cs
  src/SFA.DAS.AssessorService.Application.Api.External/SwaggerHelpers/Examples/UpdateCertificateExample.cs
  src/SFA.DAS.AssessorService.Application.Api.External/SwaggerHelpers/UpdateOptionalParamatersWithDefaultValues.cs
  src/SFA.DAS.AssessorService.Application.Api.External/appsettings.json
  src/SFA.DAS.AssessorService.Application.Api.External/nlog.config
  src/SFA.DAS.AssessorService.Application.Api.External/web.config
Labels: Requires testing

#45 ON-2249 select learner no cert bug
  src/SFA.DAS.AdminService.Web/Views/Search/Select.cshtml
  src/SFA.DAS.AssessorService.Api.Types/Models/LearnerDetail.cs
Labels: Tested

#50 ON-862 Fixed issue with Org name not displaying on the search result screen
  src/SFA.DAS.AdminService.Web/Controllers/SearchController.cs
  src/SFA.DAS.AdminService.Web/Views/Search/Results.cshtml
Labels: Ready for Release, Tested
